---
# vars file for cluster_mysql
mysql_port: "3306"
mysql_datadir: "/opt/xzx/data/mysql"
socket: "/var/lib/mysql/mysql.sock"
log_error: "/opt/xzx/log/mysql/mysqld.log"
pid_file: "/var/run/mysqld/mysqld.pid"
max_connections: "5000"
open_files_limit: "65535"
table_open_cache: "128"
max_allowed_packet: "4"
binlog_cache_size: "1"
max_heap_table_size: "8"
tmp_table_size: "16"
character_set_server: "utf8mb4"
read_buffer_size: "2"
read_rnd_buffer_size: "8"
sort_buffer_size: "8"
join_buffer_size: "28"
thread_cache_size: "8"
query_cache_type: "1"
query_cache_size: "8"
query_cache_limit: "2"
myisam_sort_buffer_size: "8"
myisam_repair_threads: "1"
interactive_timeout: "28800"
wait_timeout: "28800"
innodb_log_file_size: "500"
key_buffer_size: "32"
######################
