apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rs-secret
spec:
  replicas: 4
  selector:
   sel: my-rs-secret
  template:
    metadata:
      labels:
         sel: my-rs-secret
    spec:
      volumes:
      - name: secret-volume
        secret:
           secretName: secret-test
      containers:
      - image: nginx
        name: my-rs-secret
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /tmp/secret
