---
#########################################################################
# tested on centos 7
# 2017-06-12
# created by : lvzhijun
# task info : pull logstash and run it
########################################################################
# base on docker_init
- name: install python-pip
  yum: name=python-pip state=present

- name: install docker-py
  pip: name=docker-py

- name: pull logstash
  docker_image:
    name: logstash:alpine

- name: mkdir
  file: path=/root/docker_logstash/ owner=root group=root mode=0755 state=directory

- name: copy logstash conf file
  template: src=nginx_access.conf dest=/root/docker_logstash/ owner=root group=root mode=0600

- name: docker run logstash
  docker:
    name: logstash
    image: logstash:alpine
    state: present
    command:  -f /root/docker_logstash
    volumes:
       - /root/docker_logstash
