---
#########################################################################
# tested on centos 7
# 2017-06-12
# created by : lvzhijun
# task info : pull logstash and run it
########################################################################
# base on docker_init
- name: useradd
  user: name=logstash

- name: install python-pip
  yum: name=python-pip state=present

- name: install docker-py
  pip: name=docker-py

- name: pull logstash
  docker_image:
    name: logstash:alpine

- name: mkdir
  file: path={{ elk_conf_path }} owner=logstash group=logstash mode=0755 state=directory

- name: copy logstash conf file
  template: src=nginx_access.conf dest={{ elk_conf_path }} owner=logstash group=logstash mode=0644

- name: docker run logstash
  docker_container:
    name: logstash
    image: logstash:alpine
    state: started
    command:  -f {{ elk_conf_path }}
    volumes:
       - "{{ elk_conf_path }}:{{ elk_conf_path }}"
       - "{{ elk_nginx_log_path }}:{{ elk_nginx_log_path }}"
