---
#########################################################################
# tested on centos 7
# 2017-06-60
# created by : lvzhijun
# 1.init k8s cluster
########################################################################
#you can make repo by yourself , pls follow http://www.jianshu.com/p/8ce11f947410 , step 1
- name: config repo
  template: src=k8s.repo dest=/etc/yum.repos.d/k8s.repo owner=root group=root mode=0640
# install kubeadm in all hosts
- name: install docker engine
  yum: name=kubeadm-{{ k8s_version }} state=present

- name: install python-pip
  yum: name=python-pip state=present

- name: install docker-py
  pip: name=docker-py

- name: docker pull etcd
  docker_image:
    name: "docker.io/4admin2root/etcd-amd64:3.0.17"
  when: inventory_hostname in groups["etcd"]

- name: docker pull quay.io/coreos/hyperkube
  docker_image:
    #name: "4admin2root/hyperkube:v{{ k8s_version }}_coreos.0"
    name: "reg-i.xzxpay.com/coreos/hyperkube:v{{ k8s_version }}_coreos.0"
  when: inventory_hostname in groups["master"]

# todo
# init etcd cluster
# reconfig kubelet.service : pod-infra-container-image
# reconfig /etc/systemd/system/kubelet.service.d/10-kubeadm.conf : from systemd to cgroupfs
# run kubeadm in commander
#
