---
#########################################################################
# tested on centos 7
# 2017-06-60
# created by : lvzhijun
# 1.init k8s cluster
########################################################################
#you can make repo by yourself , pls follow http://www.jianshu.com/p/8ce11f947410 , step 1
- name: config repo
  template: src=k8s.repo dest=/etc/yum.repos.d/k8s.repo owner=root group=root mode=0640
# install kubeadm in all hosts
- name: install docker engine
  yum: name=kubeadm-{{ k8s_version }} state=present

- name: install python-pip
  yum: name=python-pip state=present

- name: install docker-py
  pip: name=docker-py

- name: docker pull etcd
  docker_image:
    name: "{{ etcd_docker_url }}"
  when: inventory_hostname in groups["etcd"]

- name: docker pull quay.io/coreos/hyperkube
  docker_image:
    name: "{{ hyperkube_docker_url }}"
  when: inventory_hostname in groups["master"]

- name: etcd_init mkdir
  file: path={{ etcd_data_dir }} state=directory mode=755

- name: generate initial-cluster
  local_action: template src=initial-cluster.j2 dest=/tmp  mode=0644

- name: load initial-cluster
  include_vars:
      file: /tmp/initial-cluster.j2

- name: etcd_init docker run
  docker_container:
    name: etcd
    image: "{{ etcd_docker_url }}"
    recreate: yes
    command: etcd -name {{ etcd_name }} -advertise-client-urls http://{{ inventory_hostname }}:2379 -listen-client-urls http://0.0.0.0:2379 -initial-advertise-peer-urls http://{{ inventory_hostname }}:2380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "{{ initial_cluster }}" -initial-cluster-state new -data-dir {{ etcd_data_dir }}
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "{{ etcd_data_dir }}:{{ etcd_data_dir }}"
  when: inventory_hostname in groups["etcd"]


# todo
# init etcd cluster
# reconfig kubelet.service : pod-infra-container-image
# reconfig /etc/systemd/system/kubelet.service.d/10-kubeadm.conf : from systemd to cgroupfs
# run kubeadm in commander
#
